version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama-data:/root/.ollama
    command: ["serve"]

  ollama-pull:
    image: ollama/ollama:latest
    container_name: ollama-pull
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: ["sh", "-c", "ollama pull llama3:7b"]

  agent:
    build: .
    container_name: chat-agent
    environment:
      OPENAI_API_KEY: "ollama"
      OPENAI_BASE_URL: "http://ollama:11434/v1"
    depends_on:
      ollama-pull:
        condition: service_completed_successfully

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - 3000:8080
    volumes:
      - openwebui-data:/app/backend/data
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy

volumes:
  ollama-data:
  openwebui-data:
